apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-load-balancer-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-load-balancer-controller
    spec:
      serviceAccountName: aws-load-balancer-controller
      containers:
        - name: aws-load-balancer-controller
          image: public.ecr.aws/eks/aws-load-balancer-controller:v2.6.2  # ✅ Correct image
          args:
            - --cluster-name=airflow
            - --ingress-class=alb
            - --aws-region=ap-northeast-1
            - --aws-vpc-id=vpc-070e4fadef1db730c
            # - --watch-namespace=dev  # optional, limit to your app namespace
